/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'James' at '11/7/16 11:34 PM' with Gradle 3.0
 *
 * @author James, @date 11/7/16 11:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
